#pragma once
#include"GutKink/Application.h"
#include"Core/Input/EulerInput.h"
#include"Core/Input/InputCodes.h"
#include"Core/Layer/EulerLayer.h"
#include"Core/Logs/EulerLog.h"
#include"ImGui/ImGuiLayer.h"
#include"Render/RendererAPI.h"
#include"Render/Renderer.h"
#include"Render/RenderCmd.h"
#include"Render/EulerBuffer.h"
#include"Render/Camera/EulerCamera.h"
#include"Render/Camera/CameraController.h"
#include"Render/EulerShader.h"
#include"Render/VertexArray.h"
#include"Core/EulerTimer.h"
#include"Render/EulerMaterial.h"
#include"Render/EulerTexture.h"
#include"Resource/ResourceLibrary.h"
//++++++++++++++++++++++++++++++++entry point+++++++++++++++++++++++++++