#pragma once
#include"GutKink/Application.h"
#include"Core/Input/EulerInput.h"
#include"Core/Input/InputCodes.h"
#include"Core/Layer/EulerLayer.h"
#include"Core/Logs/EulerLog.h"
#include"Core/EulerTimer.h"
#include"Core/EulerInstrumentor.h"
#include"ImGui/ImGuiLayer.h"
#include"Render/Vertices/EulerVertices.h"
#include"Render/RendererAPI.h"
#include"Render/Renderer.h"
#include"Render/Render2D/Renderer2D.h"
#include"Render/RenderCmd.h"
#include"Render/EulerBuffer.h"
#include"Render/EulerShader.h"
#include"Render/VertexArray.h"
#include"Render/EulerMaterial.h"
#include"Render/EulerTexture.h"
#include"Render/FrameBuffer.h"
#include"Resource/ResourceLibrary.h"

#include"Render/Camera/EulerCamera.h"
#include"Render/Camera/OrthoCamera.h"
#include"Render/Camera/PerspectiveCamera.h"
#include"Render/Camera/CameraController.h"

#include"Game/EulerScene.h"
#include"Game/Component/Component.h"
#include"Game/EulerObject.h"
//++++++++++++++++++++++++++++++++entry point+++++++++++++++++++++++++++